#!/bin/bash

# Download latest stable Plume libraries
rm -rf lib && mkdir -p lib && rm -rf ./tmp && mkdir -p ./tmp && cd ./tmp \
  && git init \
  && git remote add origin https://github.com/plume-oss/plume.git \
  && git fetch --depth 1 origin develop \
  && git reset --hard FETCH_HEAD \
  && ./gradlew oneJar \
  && mv ./build/libs/plume-X.X.X.jar ../lib/plume-X.X.X.jar \
  && cd .. && rm -rf ./tmp
